backend:
  name: git-gateway
  branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "platillos"
    label: "Menú"
    folder: "src/content/platillos"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Nombre del Platillo", name: "title", widget: "string"}
      - {label: "Descripción", name: "descripcion", widget: "text"}
      - {label: "Precio", name: "precio", widget: "number", value_type: "float"}
      - {label: "Foto", name: "imagen", widget: "image"}